version: "3.0"
services:
  db:
    container_name: "database"
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - custom
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
networks:
  custom:
    driver: bridge