version: "3.0"
services:
  db:
    container_name: "database"
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - custom
  db_test:
    container_name: "database_test"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
networks:
  custom:
    driver: bridge